name: cheeta
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.3
  google_sign_in: ^5.3.1
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.1.6  
flutter_native_splash:   
  color: "#FFFFFF"   
  image: assets/images/cheeta.png   
  android: true   
  ios: true   
  android_gravity: center
  
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
